#!/usr/bin/env python3
"""scope-gate.py - fail if a branch changes any path outside the step's allowed set.

Usage (run inside the repository):
  python3 scope-gate.py --allowed <file> [--target <ref> | --base <commit>]

  --allowed FILE  Repository-relative paths the step may change, one per line: the prompt's
                  section 3 MAY list, including outputs regenerated by approved tooling.
                  Blank lines and lines starting with '#' are ignored. An allowed path does
                  not have to change.
  --target REF    Default: origin/main. The base is the merge-base of HEAD and REF,
                  recomputed on every run, so a rebase needs no manual update.
  --base COMMIT   Use this commit as the base instead (must be an ancestor of HEAD).

Four kinds of change are checked: committed on the branch since the base, staged, unstaged,
and untracked files that git does not ignore. A rename counts as removing the old path and
adding the new one, so both paths must be allowed. Paths are read NUL-separated, so spaces
and tabs in names are safe; names containing newlines cannot be listed in FILE.

Exit codes: 0 every changed path is allowed; 1 out-of-scope paths (listed on stderr);
2 bad arguments or a failed git command (the gate never passes on an error).
"""
import argparse
import os
import subprocess
import sys


def git(*args):
    try:
        return subprocess.run(["git", *args], check=True, capture_output=True).stdout
    except subprocess.CalledProcessError as e:
        sys.stderr.write(f"scope-gate: git {' '.join(args)} failed: {e.stderr.decode(errors='replace').strip()}\n")
        sys.exit(2)


def main():
    ap = argparse.ArgumentParser(description="Fail if a branch changes paths outside the allowed set.")
    ap.add_argument("--allowed", required=True)
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--target", default="origin/main")
    group.add_argument("--base")
    a = ap.parse_args()

    try:
        with open(a.allowed, encoding="utf-8") as fh:
            allowed = {ln.rstrip("\r\n") for ln in fh if ln.strip() and not ln.lstrip().startswith("#")}
    except OSError as e:
        sys.stderr.write(f"scope-gate: cannot read {a.allowed}: {e}\n")
        sys.exit(2)

    os.chdir(os.fsdecode(git("rev-parse", "--show-toplevel").rstrip(b"\n")))
    if a.base:
        base = git("rev-parse", "--verify", f"{a.base}^{{commit}}").decode().strip()
        if subprocess.run(["git", "merge-base", "--is-ancestor", base, "HEAD"]).returncode != 0:
            sys.stderr.write(f"scope-gate: base {a.base} is not an ancestor of HEAD\n")
            sys.exit(2)
    else:
        base = git("merge-base", "HEAD", a.target).decode().strip()

    diff = ["diff", "--name-only", "--no-renames", "--ignore-submodules=none", "-z"]
    changed = set()
    for cmd in ([*diff, f"{base}...HEAD", "--"], [*diff, "--cached", "--"], [*diff, "--"],
                ["ls-files", "--others", "--exclude-standard", "-z", "--"]):
        changed.update(p for p in git(*cmd).split(b"\0") if p)

    unexpected = sorted(changed - {os.fsencode(p) for p in allowed})
    print(f"scope-gate: base {base[:12]}, {len(changed)} changed path(s), {len(allowed)} allowed")
    if unexpected:
        sys.stderr.write("FAIL: out-of-scope paths:\n")
        for p in unexpected:
            sys.stderr.write(f"  {os.fsdecode(p)!r}\n")
        sys.exit(1)
    print("PASS: every changed path is allowed.")


if __name__ == "__main__":
    main()
